### ISSUE TITLE
npm publish 0.0.4

### ISSUE THREAD

**Issue by danschumann** [danmactough/node-htmlencode#2]
You still can't see repo in npmjs.org.  Can you `npm publish` please?

**Comment by danmactough** [comment]
Chillax, dude. I can't do that from my phone. :)

**Comment by danmactough** [comment]
Published v0.0.4

**Comment by danschumann** [comment]
lol yea I was just reminding you cuz I figured you'd have to do it later.  Thanks!

**Comment by danmactough** [comment]
I'm feeling like a boss, merging a PR from my phone, then within moments...
Good times... :)
